spring :
  config:
    activate:
      on-profile: prod
  redis:
    # k8s의 redis 서비스명을 지정
    host: redis-service
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB_HOST는 k8s의 Secret 내의 Key이름과 일치
    url: jdbc:mysql://${DB_HOST}:3306/ordersystem?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
jwt:
  expiration: 1000
  secretKey: ${SECRET_KEY}
  expirationRt: 288000
  secretKeyRt: ${SECRET_KEY_RT}
