
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-choi1992-com-tls
  namespace: argocd
spec:
  secretName: argo-choi1992-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.choi1992.shop
  dnsNames:
  - argo.choi1992.shop